trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- group: Site

steps:

- checkout: self
  fetchDepth: 1

- template: templates/build-steps.yml

- template: templates/deployment-steps.yml
  parameters:
    AzureSubscription: $(Site.ServiceConnection)
    StorageAccount: $(Site.StorageAccountName)
    SiteFolder: $(siteFolder)
